filter:
    excluded_paths:
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
        - '*.min.js'
        - '*/vendor/*'
        - 'web/config.php'
        - 'bin/*'
        - 'var/*'
        - 'composer.lock'
        - 'src/*/DataFixtures'
checks:
    php: true
    javascript: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
build:
    tests:
        before:
            - cp app/config/parameters.yml.scrutinizer app/config/parameters.yml
            - php bin/console doctrine:database:create --env=test
            - php bin/console doctrine:schema:create --env=test
            - php bin/console doctrine:fixtures:load -n --env=test
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.xml --debug'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
    environment:
        php: '7.0.8'
        mysql: 5.6             # 5.5 or 5.6 or 5.7
