language: php
php:
  - '7.0'
  - '7.1'

addons:
  mariadb: '10.0'
services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - TEST_SUITE=command
  - TEST_SUITE=controller
git:
  depth: 3
#before_install
#install:

before_script:
  - phpenv config-rm xdebug.ini
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --prefer-dist
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - "phpdbg -qrr ./vendor/bin/phpunit  --coverage-text --testsuite $TEST_SUITE"

#after_script

notifications:
  slack: tuo-result-page:0coSUCLt6GJaQRYoGfBMXfrH