language: php
php:
  - 7
  - 7.1

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - TEST_SUITE=Integration
    - TEST_SUITE=Unit
git:
  depth: 3
before_install:
  - phpenv config-rm xdebug.ini
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update -q

install:
  - if [ -z "$dependencies" ]; then composer install  --prefer-dist ; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-dist -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update  --prefer-dist -n; fi;

before_script:
  - if [ "$TEST_SUITE" = "Integration" ]; php bin/console doctrine:database:create --env=test ; fi;
  - if [ "$TEST_SUITE" = "Integration" ]; php bin/console doctrine:schema:create --env=test ; fi;
  - if [ "$TEST_SUITE" = "Integration" ]; php bin/console doctrine:fixtures:load -n  --env=test ; fi;

script:
  - "phpdbg -qrr ./vendor/bin/phpunit --testsuite $TEST_SUITE"

#after_script

notifications:
  slack: tuo-result-page:0coSUCLt6GJaQRYoGfBMXfrH
