language: php
php:
  - 5.6
  - 7
  - 7.1

matrix:
  include:
    - php: 5.6
      env: dependencies=lowest
    - php: 7
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest
    - php: 7
      env: dependencies=highest
    - php: 7.1
      env: dependencies=highest

addons:
  mariadb: '10.0'
services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - TEST_SUITE=command
  - TEST_SUITE=controller
git:
  depth: 3
#before_install
#install:

before_script:
  - phpenv config-rm xdebug.ini
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update -q
    - if [ -z "$dependencies" ]; then composer install  --prefer-dist ; fi;
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-dist -n; fi;
    - if [ "$dependencies" = "highest" ]; then composer update  --prefer-dist -n; fi;
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - "phpdbg -qrr ./vendor/bin/phpunit  --coverage-text --testsuite $TEST_SUITE"

#after_script

notifications:
  slack: tuo-result-page:0coSUCLt6GJaQRYoGfBMXfrH