services:
    loki_tuo_result.reader:
        class: LokiTuoResultBundle\Service\Reader\Service
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            cardManager: "@loki_tuo_result.owned_card.manager"
        #arguments: ["@service_id", "plain_value", %parameter%]

    loki_tuo_result.card.reader:
        class: LokiTuoResultBundle\Service\CardReader\Service
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.card.persister:
        class: LokiTuoResultBundle\Service\CardReader\Persister
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.owned_card.mass_sim_reader:
        class: LokiTuoResultBundle\Service\OwnedCards\MassSimReader
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            ownedCardManager: "@loki_tuo_result.owned_card.manager"

    loki_tuo_result.owned_card.manager:
        class: LokiTuoResultBundle\Service\OwnedCards\Service
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.persister.database:
        class: LokiTuoResultBundle\Service\Persister\DatabasePersister
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.persister.null:
        class: LokiTuoResultBundle\Service\Persister\NullPersister

    loki_tuo_result.battlegroundeffect.reader:
        class: LokiTuoResultBundle\Service\BattleGroundEffectReader\Service
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.player.manager:
        class: LokiTuoResultBundle\Service\PlayerManager\Service
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.simulation.manager:
        class: LokiTuoResultBundle\Service\Simulation\Service
        arguments:
            twig: '@templating'
        #arguments: ["@service_id", "plain_value", %parameter%]

#    loki_tuo_result.vpc_simulation.manager:
#        class: LokiTuoResultBundle\Service\VpcSImulation\Service
#        arguments:
#            buzz: '@buzz'
#            vpc_url: "%vpc_url%"

    loki_tuo_result.password_resetting:
        class: LokiTuoResultBundle\EventListener\RegistrationListener
        arguments: ['@logger', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    app.exception_listener:
        class: LokiTuoResultBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    app.player_voter:
        class: LokiTuoResultBundle\Security\PlayerVoter
        arguments: ['@logger']
        tags:
            - { name: security.voter }
        public: false

    app.guild_voter:
        class: LokiTuoResultBundle\Security\GuildVoter
        arguments: ['@logger']
        tags:
            - { name: security.voter }
        public: false