services:
    loki_tuo_result.reader:
        class: App\LokiTuoResultBundle\Service\Reader\Service
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@loki_tuo_result.owned_card.manager"
            - "@logger"
        #arguments: ["@service_id", "plain_value", %parameter%]

    loki_tuo_result.card.reader:
        class: App\LokiTuoResultBundle\Service\CardReader\Service
        arguments:
            - "@doctrine.orm.entity_manager"

    loki_tuo_result.card.persister:
        class: App\LokiTuoResultBundle\Service\CardReader\Persister
        arguments:
            - "@doctrine.orm.entity_manager"

    loki_tuo_result.owned_card.mass_sim_reader:
        class: App\LokiTuoResultBundle\Service\OwnedCards\MassSimReader
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@loki_tuo_result.owned_card.manager"

    loki_tuo_result.owned_card.manager:
        class: App\LokiTuoResultBundle\Service\OwnedCards\Service
        arguments:
            - "@doctrine.orm.entity_manager"

    loki_tuo_result.persister.database:
        class: App\LokiTuoResultBundle\Service\Persister\DatabasePersister
        arguments:
            - "@doctrine.orm.entity_manager"

    loki_tuo_result.persister.null:
        class: App\LokiTuoResultBundle\Service\Persister\NullPersister

    loki_tuo_result.battlegroundeffect.reader:
        class: App\LokiTuoResultBundle\Service\BattleGroundEffectReader\Service
        arguments:
            - "@doctrine.orm.entity_manager"

    loki_tuo_result.player.manager:
        class: App\LokiTuoResultBundle\Service\PlayerManager\Service
        arguments:
            - "@doctrine.orm.entity_manager"

    loki_tuo_result.simulation.manager:
        class: App\LokiTuoResultBundle\Service\Simulation\Service
        arguments:
            - '@templating'
        #arguments: ["@service_id", "plain_value", %parameter%]

    loki_tuo_result.vpc_simulation.manager:
        class: App\LokiTuoResultBundle\Service\VpcSImulation\Service
        arguments:
            - '@buzz'
            - "%vpc_url%"

    loki_tuo_result.password_resetting:
        class: App\LokiTuoResultBundle\EventListener\RegistrationListener
        arguments: ['@logger', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    loki_tuo_result.tyrant_connector:
        class: App\LokiTuoResultBundle\Service\TyrantApiConnector\Service
        arguments: ['@monolog.logger.tu_api', '%tu_api_hash_salt%', '%tu_api_signature_salt%']

    app.exception_listener:
        class: App\LokiTuoResultBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    app.player_voter:
        class: App\LokiTuoResultBundle\Security\PlayerVoter
        arguments: ['@logger']
        tags:
            - { name: security.voter }
        public: false

    app.guild_voter:
        class: App\LokiTuoResultBundle\Security\GuildVoter
        arguments: ['@logger']
        tags:
            - { name: security.voter }
        public: false
    app.message_voter:
        class: App\LokiTuoResultBundle\Security\MessageVoter
        arguments: ['@logger']
        tags:
            - { name: security.voter }
        public: false
    loki_tuo_result.queue_item.manager:
        class: App\LokiTuoResultBundle\Service\QueueItem\Service
        arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@translator"
    loki_tuo_result.tu_api.battle.producer:
        class: App\LokiTuoResultBundle\Service\RabbitMq\TuApiProducer
        arguments:
          - "@old_sound_rabbit_mq.tu_api.battle_producer"
          - "@doctrine.orm.default_entity_manager"
          - "@loki_tuo_result.queue_item.manager"
    loki_tuo_result.tu_api.update.producer:
        class: App\LokiTuoResultBundle\Service\RabbitMq\TuApiProducer
        arguments:
          - "@old_sound_rabbit_mq.tu_api.update_producer"
          - "@doctrine.orm.default_entity_manager"
          - "@loki_tuo_result.queue_item.manager"
    loki_tuo_result.tu_api.battle.consumer:
        class: App\LokiTuoResultBundle\Service\RabbitMq\TuBattleConsumer
        arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@loki_tuo_result.tyrant_connector"
          - "@monolog.logger.tu_api"
          - "@loki_tuo_result.queue_item.manager"
    loki_tuo_result.tu_api.update.consumer:
        class: App\LokiTuoResultBundle\Service\RabbitMq\TuUpdateInventoryConsumer
        arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@loki_tuo_result.tyrant_connector"
          - "@monolog.logger.tu_api"
          - "@loki_tuo_result.owned_card.manager"
          - "@loki_tuo_result.queue_item.manager"
