services:
    loki_tuo_result.reader:
        class: LokiTuoResultBundle\Service\Reader\Service
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        #arguments: ["@service_id", "plain_value", %parameter%]
