services:
    loki_tuo_result.reader:
        class: LokiTuoResultBundle\Service\Reader\Service
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        #arguments: ["@service_id", "plain_value", %parameter%]

    loki_tuo_result.card.reader:
        class: LokiTuoResultBundle\Service\CardReader\Service
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.card.persister:
        class: LokiTuoResultBundle\Service\CardReader\Persister
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.owned_card.mass_sim_reader:
        class: LokiTuoResultBundle\Service\OwnedCards\MassSimReader
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.simulation.manager:
        class: LokiTuoResultBundle\Service\Simulation\Service
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    loki_tuo_result.user.manager:
        class: LokiTuoResultBundle\Service\UserService\Service
        arguments:
            guilds: "%guilds%"
        #arguments: ["@service_id", "plain_value", %parameter%]
