loki_user:
    resource: "@LokiUserBundle/Controller/"
    type:     annotation
    prefix:   /

loki_tuo_result:
    resource: "@LokiTuoResultBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"