# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    session_memcached_host:     localhost
    session_memcached_port:     11211
    session_memcached_prefix:   sess
    session_memcached_expire:   3600
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    session.memcached:
        class: Memcached
        arguments:
            persistent_id: "%session_memcached_prefix%"
        calls:
            - [ addServer, [ "%session_memcached_host%", "%session_memcached_port%" ]]

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ["@session.memcached", { prefix: "%session_memcached_prefix%", expiretime: "%session_memcached_expire%" }]