# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    session_memcached_host:     localhost
    session_memcached_port:     11211
    session_memcached_prefix:   sess
    session_memcached_expire:   3600
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
