services:
#    loki_user.example:
#        class: LokiUserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    loki.user.user.manager:
        class: LokiUserBundle\Service\UserService\Service
        arguments:
            guilds: "%guilds%"
            registration_codes: "%registration_codes%"

    app.form.registration:
        class: LokiUserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.user_voter:
        class: LokiUserBundle\Security\UserVoter
        tags:
            - { name: security.voter }
        public: false